Repository yamagata-developers-society/blog, pull requests merged in 2019-12, with the labels that each got.

#18 [Feat] Add content for improving SEO and JP access
  src/pages/about.tsx
  src/styles/shared.ts
  src/website-config.ts
Labels: canReview

#19 Mei_w blog
  src/content/author.yaml
  src/content/avatars/mei_w.jpg
  src/content/fascination-of-ydm-from-beginner.md
  src/content/img/authors/mei_w-cover.jpg
  src/content/img/posts/fascination-of-ydm-from-beginner/cover.jpg
  src/content/img/posts/fascination-of-ydm-from-beginner/picture.jpg
Labels: canReview

#16 [Article] React hooks color picker [DO NOT MERGE UNTIL 12/5]
  src/content/img/posts/react-hooks-color-picker/demo-screenshot.jpg
  src/content/img/posts/react-hooks-color-picker/post-hero.jpg
  src/content/react-hooks-color-picker.md
  src/global-styles/index.css
  src/layouts/index.tsx
Labels: canReview, doNotMerge

#28 [Chore] add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: LGTM

#25 [Feat] Add prism syntax highlighting
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/content/react-hooks-color-picker.md
  src/content/stateful-components-vanilla-js.md
  src/global-styles/index.css
  src/pages/about.tsx
Labels: canReview

#29 [Article] build slide in modal react [DO NOT MERGE UNTIL 12/13]
  src/content/author.yaml
  src/content/img/posts/react-hooks-color-picker/banner.jpg
  src/content/img/posts/react-hooks-color-picker/preview-1.jpg
  src/content/img/posts/react-hooks-slide-in-modal/banner.jpg
  src/content/img/posts/react-hooks-slide-in-modal/preview-1.png
  src/content/react-hooks-color-picker.md
  src/content/react-hooks-slide-in-modal.md
  src/templates/author.tsx
Labels: LGTM

#31 [Chore] fix social meta tags
  README.md
  src/content/author.yaml
  src/content/img/posts/react-hooks-color-picker/banner.jpg
  src/content/react-hooks-color-picker.md
  src/content/react-hooks-slide-in-modal.md
  src/content/stateful-components-vanilla-js.md
  src/content/tag.yaml
  src/pages/about.tsx
  src/pages/index.tsx
  src/templates/author.tsx
  src/templates/post.tsx
  src/templates/tags.tsx
  src/website-config.ts
Labels: LGTM

#34 [Feature] add active link style to site nav
  src/components/header/SiteNav.tsx
  src/pages/about.tsx
  src/pages/index.tsx
  src/templates/tags.tsx
Labels: canReview
